spring.application.name=archivebook
spring.main.allow-bean-definition-overriding=true
spring.security.user.name=admin
spring.security.user.password=admin
spring.datasource.url=jdbc:postgresql://localhost:5432/archivebook
spring.datasource.username=postgres
spring.datasource.password=postgre
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
server.address=0.0.0.0
jwt.private.key=classpath:app.key
jwt.public.key=classpath:app.pub
# Tama\u00f1o m\u00e1ximo del archivo individual
spring.servlet.multipart.max-file-size=10MB
# Tama\u00f1o m\u00e1ximo de la petici\u00f3n completa (por si subes varios a la vez)
spring.servlet.multipart.max-request-size=10MB
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG