spring.application.name=archivebook
spring.main.allow-bean-definition-overriding=true
spring.security.user.name=admin
spring.security.user.password=admin
spring.datasource.url=jdbc:postgresql://localhost:5432/archivebook
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
jwt.private.key=classpath:app.key
jwt.public.key=classpath:app.pub